plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    // YACL
    implementation "maven.modrinth:yacl:${yacl_version}-fabric"
    implementation "org.quiltmc.parsers:json:0.3.0"
    implementation "org.quiltmc.parsers:gson:0.3.0"
    include "org.quiltmc.parsers:json:0.3.0"
    include "org.quiltmc.parsers:gson:0.3.0"
    implementation "com.terraformersmc:modmenu:${mod_menu_version}"

    // Echo Chest
    compileOnly "maven.modrinth:echo-chest:${echo_chest_fabric_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}
