plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // YACL
    implementation "maven.modrinth:yacl:${yacl_version}-neoforge"

    // EMI
    compileOnly "dev.emi:emi-neoforge:${emi_version}"
    runtimeOnly "dev.emi:emi-neoforge:${emi_version}"

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.6'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.0'
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}
